### ISSUE TITLE
能所標誌不能跨文本

### ISSUE THREAD

**Issue by huiping2015** [ksanaforge/pannaloka#11]
![image](https://cloud.githubusercontent.com/assets/15063452/10579611/9fab1f32-76ab-11e5-8f34-e4b195f3d953.png)

**Comment by yapcheahshen** [comment]
我試了可以呀

2015-10-19 21:57 GMT+08:00 huiping2015 notifications@github.com:

**Comment by huiping2015** [comment]
我試不行,沒法重覆標

**Comment by yapcheahshen** [comment]
請用錄影說明.

2015-10-19 22:23 GMT+08:00 huiping2015 notifications@github.com:

**Comment by yapcheahshen** [comment]
fixed
select a range inside markup will not edit the markup
