### ISSUE TITLE
加名相-情境標誌

### ISSUE THREAD

**Issue by huiping2015** [ksanaforge/pannaloka#13]
一個名相對多個情境，可以跨段，跨文本

**Comment by yapcheahshen** [comment]
情境(二階標記)的製作：
一）先選取一段文字，選擇「情境」
二）選取一個或多個現有一階標記(直接標內文的標記)
三）按「定義情境」

情境標記的呈現：
一）選擇一個一階標記
二）最上方會顯示含有此一階標記的所有二階標記。
三）選二階標記，會顯示所有包含的一階標記。

**Comment by yapcheahshen** [comment]
done
